language: elixir
otp_release:
  - 19.0
elixir:
  - 1.3.4
  - 1.4.0
branches:
  only:
    - master
    - development
env:
  global:
    - MIX_ENV=test
    - PULL_REQUEST_ID=$TRAVIS_PULL_REQUEST
    - DOCTESTS=true
before_script:
  - rvm install ruby-2.3.1
  - gem install pronto-credo
script:
  - if [ $PULL_REQUEST_ID != false && -z "$GITHUB_ACCESS_TOKEN" ]; then pronto run -f github_pr github_status; fi
  - mix coveralls.travis
services:
  - redis-server
  - memcached
cache:
  directories:
    - "/home/travis/.rvm/"
